spring:
  application:
    name: poustfit-server
  datasource:
    host: localhost
    port: 5432
    database: poustfit
    username: poustfit
    password: poustfit
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  servlet:
    context-path: /poustfit-server
properties:
  clientHost: http://localhost:5173
  jwt-secret-key: bWkgY2xhdmUgc3VwZXIgc2VndXJhIDEyMzQ1MjQ1MjIzMTEzMw==
  expiration-in-minutes: 30
  jwt-cookie-name: TOKEN
  max-file-size: 20
  media-path-user: C:\Users\migue\HACKUDC\media\user\
  media-path-post: C:\Users\migue\HACKUDC\media\post\
  inditex-api-url: https://api.inditex.com/pubvsearch/products
  auth-url: https://auth.inditex.com:443/openam/oauth2/itxid/itxidmp/access_token
  inditex-client: oauth-mkplace-oauthzhclqppuecgsquoxwlpropro
  inditex-password: b~C1-Q]P?H{:zgOC
  imgur-url: https://api.imgur.com/3/upload
  imgur-client: e31f050b518e308
  imgbb-key: 78bea06a4a5b503785fca0a11cb82635
  imgbb-url: https://api.imgbb.com/1/upload

logging:
  level:
    web: debug